import { defineAttributeGroup } from "../../types";

/** Horns — visible fantasy morphology, gated by bodyFeatures group "horns". */
export const hornsGroup = defineAttributeGroup("horns", [
  {
    id: "horns.shape",
    label: "Horn shape",
    kind: "physical",
    category: "horns",
    valueType: "enum",
    description: "Overall horn silhouette.",
    mutability: "inherent",
    allowedValues: ["short_curved", "swept_back", "straight", "spiraled", "branching", "ram", "antlered", "jagged"],
    bodyLocationId: "horns",
    aliases: ["horn shape", "curved horns", "spiral horns", "ram horns", "antlers"],
    promptHints: ["Visible fantasy morphology; describe as part of the always-visible appearance."],
  },
  {
    id: "horns.length",
    label: "Horn length",
    kind: "physical",
    category: "horns",
    valueType: "enum",
    description: "How prominent the horns are.",
    mutability: "inherent",
    allowedValues: ["nubs", "short", "medium", "long"],
    bodyLocationId: "horns",
    aliases: ["horn length"],
  },
  {
    id: "horns.count",
    label: "Horn count",
    kind: "physical",
    category: "horns",
    valueType: "enum",
    description: "How many horns and how they are arranged.",
    mutability: "inherent",
    allowedValues: ["single", "pair", "multiple_pairs", "crown"],
    bodyLocationId: "horns",
    aliases: ["horn count", "number of horns"],
  },
  {
    id: "horns.texture",
    label: "Horn texture",
    kind: "physical",
    category: "horns",
    valueType: "enum",
    description: "Surface character of the horns.",
    mutability: "inherent",
    allowedValues: ["smooth", "ridged", "gnarled", "polished"],
    bodyLocationId: "horns",
    aliases: ["horn texture"],
  },
  {
    id: "horns.color",
    label: "Horn color",
    kind: "physical",
    category: "horns",
    valueType: "text",
    description: "Horn color or material impression.",
    mutability: "inherent",
    bodyLocationId: "horns",
    aliases: ["horn color"],
    promptHints: ["Usually non-skin material — e.g. obsidian black, bone white, ivory, blood-red, iridescent."],
  },
]);
