import { defineAttributeGroup } from "../../types";
import { MATERIAL_COLORS } from "../../shared-values";

/** Tail — visible fantasy morphology, gated by bodyFeatures group "tail". */
export const tailGroup = defineAttributeGroup("tail", [
  {
    id: "tail.type",
    label: "Tail type",
    kind: "physical",
    category: "tail",
    valueType: "enum",
    description: "The structural style of the tail.",
    mutability: "inherent",
    allowedValues: ["spaded", "reptilian", "feline", "prehensile", "serpentine", "fox", "draconic", "scorpion"],
    bodyLocationId: "tail",
    aliases: ["tail type", "spaded tail", "demonic tail", "fox tail", "serpent tail"],
    promptHints: ["Visible fantasy morphology; describe as part of the always-visible appearance."],
  },
  {
    id: "tail.length",
    label: "Tail length",
    kind: "physical",
    category: "tail",
    valueType: "enum",
    description: "How long the tail is relative to the body.",
    mutability: "inherent",
    allowedValues: ["short", "medium", "long", "very_long"],
    bodyLocationId: "tail",
    aliases: ["tail length"],
  },
  {
    id: "tail.color",
    label: "Tail color",
    kind: "physical",
    category: "tail",
    valueType: "enum_list",
    description: "Tail color, pattern, or surface material only — never size or shape. One or two from the material palette.",
    mutability: "inherent",
    allowedValues: [...MATERIAL_COLORS],
    bodyLocationId: "tail",
    aliases: ["tail color"],
    promptHints: ["e.g. matches_skin, green (scaled), russet (fur), jet_black + crimson (a red spade)."],
  },
  {
    id: "tail.tip",
    label: "Tail tip",
    kind: "physical",
    category: "tail",
    valueType: "enum",
    description: "Distinctive tail ending.",
    mutability: "inherent",
    allowedValues: ["spade", "tuft", "tapered", "barbed", "forked", "fluffy", "stinger"],
    bodyLocationId: "tail",
    aliases: ["tail tip", "spade tip"],
  },
]);
