import type { PersonalityTraitDefinition } from "./types";

/**
 * Starter trait vocabulary (docs/developer-notes/personality-and-state.spec.md §3).
 * The registry is the contract, not this list — adding a trait is a one-entry data
 * edit + the registry-invariant test. Grouped by category (kept in one file while
 * the set is small; split per category file like attributes if it grows).
 *
 * Most traits are **disposition guidance** in v1 (they render as bands in the cached
 * disposition block and steer the forge); their *state coupling* wires in progressively
 * — the social-reaction `traitScale` here (Slice 3, via `modulation.ts`), meter/mood
 * baselines in Slice 4, affinity gain/decay in Slice 5. `modulates` records that intent.
 *
 * Bipolar bands span −100..100 in three to four steps; unipolar would span 0..100.
 * Every trait's last band covers +100 so every value maps.
 */
export const traitDefinitions: readonly PersonalityTraitDefinition[] = [
  // ─── temperament ──────────────────────────────────────────────────────────
  {
    id: "temperament.warmth",
    category: "temperament",
    label: "Warmth",
    description: "How readily the character shows affection and care (cold ↔ warm).",
    axis: "bipolar",
    default: 0,
    mutability: "core",
    bands: [
      { max: -34, label: "cold", promptHint: "slow to show affection; keeps feeling at arm's length" },
      { max: 33, label: "reserved", promptHint: "measured warmth; affection is earned, not given freely" },
      { max: 100, label: "warm", promptHint: "openly affectionate and caring" },
    ],
    modulates: [{ target: "affinity", aspect: "gain", note: "warmth amplifies positive affinity moves (Slice 5)" }],
    lexicon: [
      { term: "cold", value: -80 },
      { term: "aloof", value: -55 },
      { term: "distant", value: -45 },
      { term: "reserved", value: -25 },
      { term: "kind", value: 55 },
      { term: "warm", value: 65 },
      { term: "affectionate", value: 75 },
      { term: "doting", value: 90 },
    ],
  },
  {
    id: "temperament.composure",
    category: "temperament",
    label: "Composure",
    description: "How steady the character stays under stress (volatile ↔ even-keeled).",
    axis: "bipolar",
    default: 0,
    mutability: "core",
    bands: [
      { max: -34, label: "volatile", promptHint: "quick to flare; emotions run hot and visible" },
      { max: 33, label: "reactive", promptHint: "feels things keenly but mostly holds it together" },
      { max: 100, label: "even-keeled", promptHint: "calm and hard to rattle; slow to anger" },
    ],
    modulates: [
      { target: "affinity", aspect: "gain", note: "composure damps the sting of negative moves" },
      { target: "meter:stress", aspect: "recovery", note: "composure speeds stress recovery (Slice 4)" },
    ],
    lexicon: [
      { term: "volatile", value: -75 },
      { term: "hot-tempered", value: -60 },
      { term: "excitable", value: -35 },
      { term: "calm", value: 50 },
      { term: "composed", value: 60 },
      { term: "even-keeled", value: 75 },
      { term: "unflappable", value: 90 },
    ],
  },
  {
    id: "temperament.confidence",
    category: "temperament",
    label: "Confidence",
    description: "How sure of herself the character carries herself (timid ↔ assured).",
    axis: "bipolar",
    default: 0,
    mutability: "core",
    bands: [
      { max: -34, label: "timid", promptHint: "hesitant, self-doubting, easily cowed" },
      { max: 33, label: "steady", promptHint: "quietly self-possessed without bravado" },
      { max: 100, label: "assured", promptHint: "self-assured and bold; speaks and acts decisively" },
    ],
    lexicon: [
      { term: "timid", value: -70 },
      { term: "insecure", value: -55 },
      { term: "self-doubting", value: -45 },
      { term: "self-assured", value: 55 },
      { term: "confident", value: 65 },
      { term: "bold", value: 80 },
    ],
  },
  {
    id: "temperament.optimism",
    category: "temperament",
    label: "Optimism",
    description: "Default emotional outlook (gloomy ↔ sunny) — the mood-baseline driver.",
    axis: "bipolar",
    default: 0,
    mutability: "core",
    bands: [
      { max: -34, label: "gloomy", promptHint: "expects the worst; a melancholy default" },
      { max: 33, label: "level", promptHint: "neither sunny nor bleak by default" },
      { max: 100, label: "sunny", promptHint: "hopeful and bright by default" },
    ],
    modulates: [{ target: "meter:mood", aspect: "baseline", note: "optimism sets the resting mood (Slice 4)" }],
    lexicon: [
      { term: "gloomy", value: -70 },
      { term: "pessimistic", value: -55 },
      { term: "melancholy", value: -45 },
      { term: "hopeful", value: 45 },
      { term: "optimistic", value: 60 },
      { term: "sunny", value: 65 },
      { term: "buoyant", value: 85 },
    ],
  },
  // ─── social ───────────────────────────────────────────────────────────────
  {
    id: "social.extraversion",
    category: "social",
    label: "Extraversion",
    description: "How much the character draws energy from company (introverted ↔ extraverted).",
    axis: "bipolar",
    default: 0,
    mutability: "core",
    bands: [
      { max: -34, label: "introverted", promptHint: "reserved in company; needs solitude to recharge" },
      { max: 33, label: "ambiverted", promptHint: "comfortable either alone or among people" },
      { max: 100, label: "extraverted", promptHint: "outgoing and energized by company" },
    ],
    lexicon: [
      { term: "withdrawn", value: -70 },
      { term: "introverted", value: -55 },
      { term: "private", value: -35 },
      { term: "sociable", value: 45 },
      { term: "outgoing", value: 60 },
      { term: "gregarious", value: 85 },
    ],
  },
  {
    id: "social.agreeableness",
    category: "social",
    label: "Agreeableness",
    description: "How accommodating vs. contrary the character is (contrary ↔ accommodating).",
    axis: "bipolar",
    default: 0,
    mutability: "core",
    bands: [
      { max: -34, label: "contrary", promptHint: "pushes back, bristles, slow to go along" },
      { max: 33, label: "frank", promptHint: "cooperative but won't just defer" },
      { max: 100, label: "accommodating", promptHint: "warm, obliging, conflict-averse" },
    ],
    modulates: [{ target: "affinity", aspect: "gain", note: "agreeableness damps how hard a dislike stings (Slice 3 traitScale)" }],
    lexicon: [
      { term: "combative", value: -70 },
      { term: "contrary", value: -60 },
      { term: "bratty", value: -50 },
      { term: "prickly", value: -40 },
      { term: "accommodating", value: 55 },
      { term: "agreeable", value: 60 },
      { term: "deferential", value: 70 },
    ],
  },
  {
    id: "social.guardedness",
    category: "social",
    label: "Guardedness",
    description: "How freely the character opens up (open ↔ guarded) — the affinity-gain damper.",
    axis: "bipolar",
    default: 0,
    mutability: "core",
    bands: [
      { max: -34, label: "open", promptHint: "candid and trusting; lets people in quickly" },
      { max: 33, label: "private", promptHint: "shares selectively; trust is earned in steps" },
      { max: 100, label: "guarded", promptHint: "walled-off; very slow to lower defenses" },
    ],
    modulates: [{ target: "affinity", aspect: "gain", note: "guardedness damps positive affinity gains (Slice 5)" }],
    lexicon: [
      { term: "open", value: -60 },
      { term: "trusting", value: -50 },
      { term: "candid", value: -35 },
      { term: "private", value: 45 },
      { term: "guarded", value: 60 },
      { term: "secretive", value: 70 },
      { term: "walled-off", value: 85 },
    ],
  },
  {
    id: "social.dominance",
    category: "social",
    label: "Dominance",
    description: "How much the character leads vs. defers (submissive ↔ dominant).",
    axis: "bipolar",
    default: 0,
    mutability: "core",
    bands: [
      { max: -34, label: "submissive", promptHint: "inclined to defer, follow, and yield" },
      { max: 33, label: "balanced", promptHint: "neither leads nor follows by default" },
      { max: 100, label: "dominant", promptHint: "likes to lead and set the terms" },
    ],
    lexicon: [
      { term: "submissive", value: -70 },
      { term: "deferential", value: -50 },
      { term: "yielding", value: -40 },
      { term: "assertive", value: 45 },
      { term: "dominant", value: 60 },
      { term: "commanding", value: 80 },
      { term: "domineering", value: 88 },
    ],
  },
  // ─── intimate (fenced; surfaces only at the intimate exposure tier) ─────────
  {
    id: "intimate.libido",
    category: "intimate",
    label: "Libido",
    description: "Baseline sexual drive (low ↔ high) — the arousal driver.",
    axis: "bipolar",
    default: 0,
    mutability: "core",
    intimate: true,
    bands: [
      { max: -34, label: "low", promptHint: "low sexual drive; rarely the initiator" },
      { max: 33, label: "average", promptHint: "an ordinary, situational drive" },
      { max: 100, label: "high", promptHint: "easily aroused; a ready, eager appetite" },
    ],
    modulates: [{ target: "meter:arousal", aspect: "baseline", note: "libido lifts the arousal baseline + slows its decay (Slice 4)" }],
    lexicon: [
      { term: "frigid", value: -80 },
      { term: "low-libido", value: -60 },
      { term: "reserved", value: -30 },
      { term: "passionate", value: 55 },
      { term: "high-libido", value: 65 },
      { term: "insatiable", value: 88 },
    ],
  },
  {
    id: "intimate.inhibition",
    category: "intimate",
    label: "Inhibition",
    description: "How restrained vs. uninhibited the character is intimately (uninhibited ↔ inhibited).",
    axis: "bipolar",
    default: 0,
    mutability: "core",
    intimate: true,
    bands: [
      { max: -34, label: "uninhibited", promptHint: "free and unembarrassed about desire and the body" },
      { max: 33, label: "modest", promptHint: "comfortable but not forward; some reserve" },
      { max: 100, label: "inhibited", promptHint: "easily embarrassed; holds back, reads as prudish" },
    ],
    lexicon: [
      { term: "shameless", value: -80 },
      { term: "uninhibited", value: -65 },
      { term: "free", value: -40 },
      { term: "modest", value: 45 },
      { term: "inhibited", value: 60 },
      { term: "prudish", value: 75 },
      { term: "repressed", value: 88 },
    ],
  },
  {
    id: "intimate.possessiveness",
    category: "intimate",
    label: "Possessiveness",
    description: "How territorial the character is over a partner (secure ↔ possessive) — the jealousy axis.",
    axis: "bipolar",
    default: 0,
    mutability: "core",
    intimate: true,
    bands: [
      { max: -34, label: "secure", promptHint: "unthreatened by rivals; gives space freely" },
      { max: 33, label: "attentive", promptHint: "notices rivals but trusts; mild protectiveness" },
      { max: 100, label: "possessive", promptHint: "territorial and quick to feel slighted by rivals" },
    ],
    modulates: [{ target: "affinity", aspect: "gain", note: "possessiveness amplifies jealousy_trigger reactions (Slice 3 traitScale)" }],
    lexicon: [
      { term: "secure", value: -55 },
      { term: "easygoing", value: -40 },
      { term: "trusting", value: -30 },
      { term: "protective", value: 45 },
      { term: "possessive", value: 60 },
      { term: "jealous", value: 70 },
      { term: "controlling", value: 88 },
    ],
  },
];
