/**
 * `@vesper/image-core` — the provider-neutral image engine.
 *
 * Everything exported here answers a question about IMAGES: what a model can
 * do, which references a render may carry and in what role, how a prompt is
 * compiled for a given profile, what an identity pack is and when it is usable,
 * how a control map is bound to a provider's real input fields, and what a
 * failure message means. Nothing here knows that Vesper has characters, chats,
 * a database, or a Next.js app — see README.md §Boundary.
 *
 * The subfolder barrels are the reading order: start at `capabilities` (what a
 * model declares), then `models` (a registry row and its per-task profiles),
 * then `render-intent` (what one render asks for), then the domains that
 * consume them.
 *
 * **This list is the package's entire public API, and it is deliberately
 * explicit.** Internal folder barrels may still use `export *` — they are
 * reading aids, not publication. The root may not: a wildcard here would make
 * every helper added to an internal barrel public without appearing in any
 * diff, and `pnpm lint:package-boundaries` fails the build if one reappears.
 * Adding an entry below is a public-API change, and reviewers should read it as
 * one.
 */

export {
  emptyImageModelAdvancedCapabilities,
  filterReservedInputFields,
  imageEditKindSchema,
  imageEditKinds,
  imageIdentityPreservationRatings,
  imageIdentityPreservationSchema,
  imageModelAdvancedCapabilitiesSchema,
  mapImageRenderControls,
  reservedImageInputFields,
  validateProviderOverrides,
} from "./capabilities";
export type {
  ImageEditKind,
  ImageIdentityPreservation,
  ImageInputBinding,
  ImageModelAdvancedCapabilities,
  ImageModelControlBindings,
  ImageReferenceRole,
} from "./capabilities";
export {
  IMAGE_TARGET_ASPECT,
  REPLICATE_VERSION_UNDISCLOSED,
  baseImageModelSlug,
  chooseAspect,
  fitReferences,
  imageAspectModes,
  imageModelProfileSchema,
  imageModelSchema,
  imageModelSurfaces,
  imageModelsForSurface,
  imageProfileCandidates,
  imageProfileOffered,
  imageProfileOperations,
  imageProfileTasks,
  imagePromptStrategies,
  imageReferenceArities,
  imageReferenceTransportSchema,
  imageReferenceTransports,
  isUndisclosedProviderVersion,
  parseAspectValue,
  preparePromptForImageModel,
  profileEligibility,
  providerVersionsDisagree,
  referenceCapacity,
  resolveImageProfile,
  withReviewedImageQuality,
} from "./models";
export type {
  ImageAspectMode,
  ImageLoraSelection,
  ImageModel,
  ImageModelProfile,
  ImageModelSurface,
  ImageProfileTask,
  ImagePromptStrategy,
  ImageReferenceArity,
  ImageReferenceTransport,
  ImageRenderControls,
  ResolvedImageProfile,
} from "./models";
export {
  IMAGE_LORA_INCOMPATIBLE,
  IMAGE_LORA_MAX_SCALE,
  IMAGE_LORA_MAX_TRIGGER_WORDS,
  IMAGE_LORA_MIN_SCALE,
  IMAGE_LORA_UNREACHABLE,
  applyImageLoraPromptAdditions,
  effectiveImageLoraSelection,
  evaluateImageLoraForRender,
  imageLoraCreateRequestSchema,
  imageLoraLocatorTypes,
  imageLoraScalesOrdered,
  imageLoraSchema,
  imageLoraUpdateRequestSchema,
  isValidImageLoraLocator,
  redactImageLoraLocator,
} from "./loras";
export type {
  ImageLora,
  ImageLoraCreateRequest,
  ImageLoraLocatorType,
  ImageLoraRefusalCode,
  ImageLoraRenderBinding,
  ImageLoraUpdateRequest,
} from "./loras";
export {
  missingRequiredControlInputs,
  missingRequiredReferenceRoles,
  planImageRender,
  planIntentReferences,
} from "./render-intent";
export type {
  DroppedImageReference,
  ImageRenderIntent,
  ImageRenderIntentCore,
  ImageRenderReference,
  ImageRenderReferenceSpec,
  ImageRenderRefusal,
  ImageRenderRuntimeFacts,
  PlanImageRenderResult,
  PlannedControlReference,
  PlannedImageRender,
} from "./render-intent";
export {
  MAX_TRIAL_PREDICTION_MS,
  TRIAL_FALLBACK_PREDICTION_MS,
  compileProfileRenderPlan,
  pinnedImageModelVersion,
  profileRenderControlsFingerprintJson,
  stableJson,
} from "./render-kernel";
export type {
  CompileProfileRenderPlanInput,
  CompileProfileRenderPlanResult,
  ProfileRenderControlsFingerprintInput,
  ProfileRenderPlan,
  PromptReferenceBinding,
} from "./render-kernel";
export {
  compileIdentityReferencePrompt,
  compileReferenceRolePrompt,
  sceneReferenceListSchema,
  sceneReferenceModeSchema,
  sceneReferenceSchema,
  sceneReferenceSources,
  sceneVisualReferenceKinds,
} from "./references";
export type {
  CompileReferenceBinding,
  SceneReference,
  SceneReferenceMode,
  SceneReferenceSource,
  SceneVisualReference,
  SceneVisualReferenceKind,
} from "./references";
export {
  HEURISTIC_V1,
  IDENTITY_CROP_POLICY_V1,
  IDENTITY_PACK_DERIVATION_VERSION,
  IDENTITY_PACK_POLICY_VERSION,
  IDENTITY_PACK_SCHEMA_VERSION,
  IDENTITY_PACK_TRIAL_PROMPT_FIXTURES,
  INTRINSIC_POLICY_V1,
  PROFILE_POLICY_DEFAULTS_V1,
  aggregateTrialGrades,
  buildIdentityPackQuality,
  buildTrialCellPlans,
  clampSelection,
  compareTrialCellKeys,
  cropPreviewLayout,
  deriveDetectorCrop,
  displayScale,
  evaluateIdentityEffectiveSize,
  evaluateIdentityPackIntrinsic,
  evaluateIdentityProfilePolicy,
  fitDisplayBox,
  heuristicCropV1,
  identityBlurScore,
  identityCropHandles,
  identityCropOutputSide,
  identityFaceDetector,
  identityPackAdminOverrideRequestSchema,
  identityPackAdminRevisionSchema,
  identityPackBatchRequestSchema,
  identityPackManualCropRequestSchema,
  identityPackResponseSchema,
  identityPackSummaryStatuses,
  identityReferenceStrategies,
  identityReferenceStrategySchema,
  imageIdentityCropMethods,
  imageIdentityPackFailureCodeSchema,
  imageIdentityPackFailureCodes,
  imageIdentityPackQualitySchema,
  imageIdentityPackStatuses,
  imageIdentityPackTrialCellSpecSchema,
  imageIdentityPackTrialCreateRequestSchema,
  imageIdentityPackTrialDiagnosticCode,
  imageIdentityPackTrialExecuteRequestSchema,
  imageIdentityPackTrialGradeRequestSchema,
  imageIdentityPackTrialRefusalCodeSchema,
  imageIdentityPackTrialResultSchema,
  imageIdentityPackTrialReviewPairSchema,
  imageIdentityPackTrialRunDetailSchema,
  imageIdentityPackTrialRunSummarySchema,
  imageIdentityPackTrialSummarySchema,
  imageIdentityPackV1Schema,
  imageIdentityPackWarningCodeSchema,
  imageIdentityPackWarningCodes,
  isAllowedIdentityPackTransition,
  isHeuristicEligibleSource,
  moveSelection,
  normalizedCropToSourcePixels,
  pairTrialCells,
  perTrialGradeDimension,
  resizeSelection,
  selectIdentityFaceCandidate,
  selectionFromCrop,
  selectionToNormalized,
  setIdentityFaceDetectorForTesting,
  sourcePixelCropSchema,
  squareSourcePixelCrop,
  toDisplayRect,
  toSourceSpace,
  trialCellComboSchema,
  trialCellCountsSchema,
  trialCellStatuses,
  trialGradeDimensions,
  trialPackVariantKey,
  trialPairGradeSchema,
  trialPromptFixtureById,
  trialRunStatusSchema,
  trialRunStatuses,
  trialVerdictSchema,
  trialVerdictValueSchema,
  trialVerdicts,
  unblindTrialPairGrade,
  validateIdentityCrop,
} from "./identity";
export type {
  DetectedFaceCandidate,
  EnsureIdentityPackInput,
  EnsureIdentityPackResult,
  EvaluateIdentityPackResult,
  IdentityCropHandle,
  IdentityFaceDetector,
  IdentityPackAdminOverrideRequest,
  IdentityPackAdminRevision,
  IdentityPackBlockedWire,
  IdentityPackIntrinsicPolicy,
  IdentityPackManualCropRequest,
  IdentityPackNormalizedCropWire,
  IdentityPackProfilePolicy,
  IdentityPackPurpose,
  IdentityPackResponseWire,
  IdentityPackSummaryStatus,
  IdentityPackSummaryWire,
  IdentityPackTrialPromptFixture,
  IdentityReferenceCandidate,
  IdentityReferenceProvenance,
  IdentityReferenceRole,
  IdentityReferenceStrategy,
  IdentitySquareSelection,
  ImageIdentityCropMethod,
  ImageIdentityPackFailureCode,
  ImageIdentityPackQuality,
  ImageIdentityPackStatus,
  ImageIdentityPackTrialCellSpec,
  ImageIdentityPackTrialCellWire,
  ImageIdentityPackTrialCreateRequest,
  ImageIdentityPackTrialGradeRequest,
  ImageIdentityPackTrialRefusalCode,
  ImageIdentityPackTrialResult,
  ImageIdentityPackTrialReviewPairWire,
  ImageIdentityPackTrialRunDetail,
  ImageIdentityPackTrialRunSummary,
  ImageIdentityPackTrialSummaryWire,
  ImageIdentityPackV1,
  ImageIdentityPackWarningCode,
  NormalizedCrop,
  PixelSize,
  SourceDimensions,
  SourcePixelCrop,
  TrialCellCounts,
  TrialCellPair,
  TrialCellPlan,
  TrialCellStatus,
  TrialGradeDimension,
  TrialGradeRecord,
  TrialPackVariantSelector,
  TrialPairGrades,
  TrialPairableCell,
  TrialRenderedCombo,
  TrialResolvedControls,
  TrialRunStatus,
  TrialStrategyComparison,
  TrialVerdict,
  TrialVerdictValue,
} from "./identity";
export {
  IMAGE_LAB_FINISHING_IDENTITY_STRATEGY,
  IMAGE_LAB_FINISHING_LORA_ONLY_RECIPE_KEY,
  IMAGE_LAB_FINISHING_RECIPE_KEY,
  IMAGE_LAB_MAX_INPUTS,
  IMAGE_LAB_UPLOAD_DATA_URL_MAX_CHARS,
  emptyImageLabSettings,
  imageLabControlKinds,
  imageLabControlMetaSchema,
  imageLabControlRole,
  imageLabControlSchema,
  imageLabCreateExperimentRequestSchema,
  imageLabDiagnosticCode,
  imageLabExperimentKinds,
  imageLabExperimentSchema,
  imageLabExperimentStatuses,
  imageLabExtractControlsRequestSchema,
  imageLabFailureCodeFromDiagnostic,
  imageLabFailureCodes,
  imageLabFinishingInstruction,
  imageLabFinishingRecipeProfile,
  imageLabFinishingVariantSchema,
  imageLabInputListSchema,
  imageLabModes,
  imageLabOutcomeDropReasons,
  imageLabOutcomeSchema,
  imageLabProbeInstruction,
  imageLabRecipeProfile,
  imageLabRecordVerdictRequestSchema,
  imageLabReviewControlRequestSchema,
  imageLabSettingsSchema,
  imageLabTwoCharacterRecipeProfile,
  imageLabTwoCharacterVerdicts,
  imageLabUploadControlRequestSchema,
  imageLabVerdictOptions,
  imageLabVerdicts,
  isImageLabControlRole,
  isImageLabControlledKind,
  isImageLabFinishableKind,
  isImageLabVerdictForKind,
  isImageLabVerdictKind,
} from "./lab";
export type {
  ImageLabControl,
  ImageLabControlGenerator,
  ImageLabControlKind,
  ImageLabControlMeta,
  ImageLabControlledKind,
  ImageLabCreateExperimentRequest,
  ImageLabExperiment,
  ImageLabExperimentKind,
  ImageLabExperimentStatus,
  ImageLabExtractControlsRequest,
  ImageLabFailureCode,
  ImageLabFinishingVariant,
  ImageLabInput,
  ImageLabInputList,
  ImageLabMode,
  ImageLabOutcome,
  ImageLabOutcomeDrop,
  ImageLabRecordVerdictRequest,
  ImageLabSettings,
  ImageLabUploadControlRequest,
  ImageLabVerdict,
} from "./lab";
export {
  AVATAR_HEIGHT,
  AVATAR_WIDTH,
  MAX_ZOOM,
  MIN_ZOOM,
  canvasRect,
  centeredOffset,
  clampOffset,
  displaySize,
} from "./geometry";
export type {
  Offset,
} from "./geometry";
export {
  attemptReferenceCount,
  classifyImageFailureMessage,
  imageFailureHealthOutcome,
  isBillingFailureMessage,
  routeSceneAttempts,
} from "./provider-interface";
export type {
  ImageFailureReason,
  ImageProviderFailure,
  ProviderRenderResult,
  SceneAttemptId,
  SceneRenderRequest,
} from "./provider-interface";
