import { defineAttributeGroup } from "../types";

export const buildGroup = defineAttributeGroup("build", [
  {
    id: "build.height",
    label: "Height",
    kind: "physical",
    category: "build",
    valueType: "enum",
    description: "Overall height as it visibly reads.",
    mutability: "inherent",
    allowedValues: [
      "very_short",
      "short",
      "below_average",
      "average",
      "above_average",
      "tall",
      "very_tall",
      "towering",
    ],
    aliases: ["height", "tall", "short", "petite"],
    promptHints: [
      'Convey height through comparison and blocking ("she has to look up at him"), never as a number.',
    ],
    coreVisual: true,
    defaultValue: "average",
  },
  {
    id: "build.frame",
    label: "Frame",
    kind: "physical",
    category: "build",
    valueType: "enum",
    description:
      "Skeletal gauge — bone structure and joint heft, independent of height and weight.",
    mutability: "inherent",
    allowedValues: [
      "delicate",
      "slight",
      "average",
      "sturdy",
      "heavy_boned",
    ],
    aliases: ["frame", "build", "figure", "physique", "bone structure"],
    coreVisual: true,
    defaultValue: "slight",
  },
  {
    id: "build.musculature",
    label: "Musculature",
    kind: "physical",
    category: "build",
    valueType: "enum",
    description: "Visible muscle development.",
    mutability: "mutable",
    allowedValues: [
      "untoned",
      "lightly_toned",
      "sinewy",
      "toned",
      "defined",
      "muscular",
      "powerfully_built",
    ],
    aliases: ["muscles", "muscle tone", "musculature"],
  },
  {
    id: "build.weight_presentation",
    label: "Weight presentation",
    kind: "physical",
    category: "build",
    valueType: "enum",
    description: "How body weight visibly presents.",
    mutability: "mutable",
    allowedValues: [
      "underweight",
      "slim",
      "average",
      "soft",
      "plump",
      "heavy",
      "very_heavy",
    ],
    aliases: ["weight", "body weight"],
    promptHints: [
      "Describe weight as silhouette and presence, never as a number or a judgement.",
    ],
  },
]);
