import { defineAttributeGroup } from "../types";

export const hairGroup = defineAttributeGroup("hair", [
  {
    id: "hair.color",
    label: "Hair color",
    kind: "physical",
    category: "hair",
    valueType: "enum",
    description: "Base hair color.",
    mutability: "mutable",
    allowedValues: [
      "black", "dark_brown", "brown", "light_brown", "auburn", "red",
      "strawberry_blonde", "blonde", "platinum", "gray", "white", "dyed_vivid",
    ],
    bodyLocationId: "hair",
    aliases: ["hair color", "ginger", "redhead", "blonde", "brunette"],
    coreVisual: true,
  },
  {
    id: "hair.length",
    label: "Hair length",
    kind: "physical",
    category: "hair",
    valueType: "enum",
    description: "Overall hair length.",
    mutability: "mutable",
    allowedValues: ["shaved", "buzzed", "short", "chin_length", "shoulder_length", "mid_back", "waist_length"],
    bodyLocationId: "hair",
    aliases: ["hair length"],
  },
  {
    id: "hair.texture",
    label: "Hair texture",
    kind: "physical",
    category: "hair",
    valueType: "enum",
    description: "Natural texture.",
    mutability: "inherent",
    allowedValues: ["straight", "wavy", "curly", "coily"],
    bodyLocationId: "hair",
    aliases: ["hair texture"],
  },
  {
    id: "hair.style",
    label: "Hair style",
    kind: "presentation",
    category: "hair",
    valueType: "text",
    description: "Current styling (\"loose braid over one shoulder\").",
    mutability: "mutable",
    bodyLocationId: "hair",
    aliases: ["hairstyle", "hair style"],
  },
]);
