import { defineAttributeGroup } from "../types";

export const hairGroup = defineAttributeGroup("hair", [
  {
    id: "hair.color",
    label: "Hair color",
    kind: "physical",
    category: "hair",
    valueType: "enum",
    description: "Base hair color.",
    mutability: "mutable",
    allowedValues: [
      "black",
      "dark_brown",
      "brown",
      "light_brown",
      "auburn",
      "red",
      "strawberry_blonde",
      "blonde",
      "platinum",
      "gray",
      "white",
      // Dye jobs — vivid, unnatural colors only achievable by dyeing (the
      // natural range above already covers brown→blonde recoloring). `dyed_vivid`
      // stays the generic catch-all for split-dye / rainbow / unspecified.
      "dyed_pink",
      "dyed_red",
      "dyed_orange",
      "dyed_yellow",
      "dyed_green",
      "dyed_teal",
      "dyed_blue",
      "dyed_purple",
      // Naturally otherworldly hair (fae, demonkin) — distinct from a dye job.
      // The vivid ones are not auto-defaulted onto a human.
      "silver",
      "rose_gold",
      "deep_violet",
      "midnight_blue",
    ],
    // A dye job is valid to pick but never an automatic default, same as the
    // otherworldly palette — no one is auto-assigned dyed hair.
    autoDefaultExcludes: [
      "dyed_pink",
      "dyed_red",
      "dyed_orange",
      "dyed_yellow",
      "dyed_green",
      "dyed_teal",
      "dyed_blue",
      "dyed_purple",
      "dyed_vivid",
      "rose_gold",
      "deep_violet",
      "midnight_blue",
    ],
    bodyLocationId: "hair",
    aliases: [
      "hair color",
      "ginger",
      "redhead",
      "blonde",
      "brunette",
      "dyed hair",
    ],
    coreVisual: true,
  },
  {
    id: "hair.length",
    label: "Hair length",
    kind: "physical",
    category: "hair",
    valueType: "enum",
    description: "Overall hair length.",
    mutability: "mutable",
    allowedValues: [
      "shaved",
      "buzzed",
      "short",
      "chin_length",
      "shoulder_length",
      "mid_back",
      "waist_length",
      "feet_length",
    ],
    bodyLocationId: "hair",
    aliases: ["hair length"],
  },
  {
    id: "hair.texture",
    label: "Hair texture",
    kind: "physical",
    category: "hair",
    valueType: "enum",
    description: "Natural curl pattern.",
    mutability: "inherent",
    allowedValues: ["straight", "wavy", "curly", "coily", "kinky"],
    bodyLocationId: "hair",
    aliases: ["hair texture"],
  },
  {
    id: "hair.quality",
    label: "Hair quality",
    kind: "physical",
    category: "hair",
    valueType: "enum",
    // Strand feel and condition — the tactile axis, distinct from the curl
    // pattern in `hair.texture`. Mutable because damage, care, age, and health
    // change it over time (a fried dye job turns hair straw-like).
    description: "Strand feel and condition.",
    mutability: "mutable",
    allowedValues: [
      "silky", "soft", "glossy", "fine", "thick",
      "coarse", "dry", "frizzy", "brittle", "straw_like",
    ],
    bodyLocationId: "hair",
    aliases: ["hair quality", "hair condition"],
  },
  {
    id: "hair.style",
    label: "Hair style",
    kind: "presentation",
    category: "hair",
    valueType: "text",
    description: 'Current styling ("loose braid over one shoulder").',
    mutability: "mutable",
    bodyLocationId: "hair",
    aliases: ["hairstyle", "hair style"],
  },
]);
