import fs from "node:fs";
import path from "node:path";
import { describe, expect, it } from "vitest";
import { repoRelative, sourceFilesUnder } from "@/server/test-support";

const ROOTS = [path.join(process.cwd(), "apps/web/src"), path.join(process.cwd(), "scripts")];
const INTERNAL_NAMES = new Set(["saveImageBuffer", "deleteChatUploads", "deleteChatAssets"]);

/**
 * Reviewed 2026-07-26; re-reviewed 2026-08-02 (image-pipeline-consolidation
 * C1): the five generation lanes no longer import `saveImageBuffer` — they run
 * on `runImagePipeline`. Its `assets.ts` coordinator imports the storage
 * writer, and `index.ts` explicitly forwards the existing public surface. Every
 * other entry is either the upload worker that minted the row it writes,
 * the route-safe owner-checking adapter, or the chat pipeline's authenticated
 * rerun / ownership-reverified delete cascade.
 *
 * Re-reviewed 2026-08-05 (image-identity-packs): the identity-pack service joins
 * the "minted the row it writes" class. It does not ride `runImagePipeline` —
 * that shell is a provider-generation sequence, and a face crop is derived
 * locally from bytes this app already stored — so it mints the hidden crop row
 * with `createImageAsset` and writes that exact id, having already re-authorized
 * the character and re-verified the source hash.
 *
 * Re-reviewed 2026-08-06 (identity-pack trial correctness pass): the trial
 * service also joins the "minted the row it writes" class — it has imported
 * `saveImageBuffer` since the slice-6 harness landed, and this census should
 * have been extended then. It cannot ride `runImagePipeline` because a trial
 * output's fate is decided AFTER storage by the durable-claim settlement CAS:
 * a settle that loses the claim race must discard the just-stored hidden
 * image rather than attach it, and the pipeline shell has no
 * store-then-maybe-discard arm. The service mints the hidden
 * `identity_trial_output` row with `createImageAsset`, writes that exact id,
 * and every read/write is owner-scoped through the run row.
 *
 * Re-reviewed 2026-08-10 (Advanced Image Lab, Stage 0): the lab's experiment
 * service joins the same "minted the row it writes" class, for the trial's own
 * reason. A `lab_output`'s fate is decided AFTER storage — the experiment row is
 * settled `succeeded` only once the bytes landed, and a write that never reached
 * `ready` DELETES the pending row rather than attaching it, which is a
 * store-then-maybe-discard arm `runImagePipeline` has no shape for. It mints the
 * hidden row with `createImageAsset`, writes that exact id, and every read and
 * write is owner-scoped through the experiment row.
 *
 * The lab's FIXTURE module (`image-lab-controls.ts`) is deliberately NOT here:
 * it is the module a route's upload body reaches, so both of its write paths go
 * through the owner-scoped `saveOwnedImageBuffer` adapter instead.
 *
 * Re-reviewed 2026-08-13 (image-lifecycle module split): the same three reviewed
 * services, at their new paths. Each write path moved into the module that owns
 * the bytes it stores — the pack service's crop derivation, the trial's per-cell
 * render, the lab's render kernel — and nothing about who may call, or why, changed.
 *
 * Re-reviewed 2026-08-23 (Image Generator): the Generator runner joins the
 * lab kernel's "minted the row it writes" class for the lab's own reason — a
 * `generator_output`'s fate is decided AFTER storage. The run row is settled
 * `succeeded` only once the bytes landed; a write that never reached `ready`
 * deletes the pending row, and a run deleted mid-render discards the orphan
 * through the owned deleter — a store-then-maybe-discard arm `runImagePipeline`
 * has no shape for. It mints the hidden row with `createImageAsset`, writes
 * that exact id, and every read/write is owner-scoped through the run row.
 *
 * Re-reviewed 2026-09-03 (character reference views): the owner-upload service
 * joins that same reviewed class. It creates the hidden `reference_view` asset,
 * validates the accepted portrait as its owner-scoped source, writes only the
 * exact asset id it minted, and then attaches that id to the reserved slot. It
 * cannot ride the provider-generation shell because the bytes are supplied by
 * the owner rather than generated by a model.
 */
const APPROVED: Readonly<Record<string, readonly string[]>> = {
  saveImageBuffer: [
    "apps/web/src/server/images/assets.ts",
    "apps/web/src/server/images/index.ts",
    "apps/web/src/server/images/identity-pack-trial-render.ts",
    "apps/web/src/server/images/image-generator-settle.ts",
    "apps/web/src/server/images/image-lab-render.ts",
    "apps/web/src/server/images/identity-pack-derive.ts",
    "apps/web/src/server/images/internal.ts",
    "apps/web/src/server/images/reference-view-upload.ts",
    "apps/web/src/server/images/route-safe.ts",
    "apps/web/src/server/images/upload.ts",
  ],
  deleteChatUploads: ["apps/web/src/server/engine/chat-pipeline.ts", "apps/web/src/server/images/index.ts", "apps/web/src/server/images/internal.ts"],
  deleteChatAssets: ["apps/web/src/server/engine/chat-delete.ts", "apps/web/src/server/images/index.ts", "apps/web/src/server/images/internal.ts"],
};

function importedInternalNames(source: string): string[] {
  const found = new Set<string>();
  const declaration = /(?:import|export)\s*{([^}]+)}\s*from\s*["'][^"']+["']/g;
  let match = declaration.exec(source);
  while (match !== null) {
    for (const specifier of (match[1] ?? "").split(",")) {
      const imported = specifier.trim().replace(/^type\s+/, "").split(/\s+as\s+/)[0]?.trim() ?? "";
      if (INTERNAL_NAMES.has(imported)) found.add(imported);
    }
    match = declaration.exec(source);
  }
  return [...found];
}

describe("internal image helper caller census", () => {
  it("contains only reviewed worker, adapter, and cascade imports", () => {
    const actual: Record<string, string[]> = Object.fromEntries([...INTERNAL_NAMES].map((name) => [name, []]));

    // `sourceFilesUnder` defaults to .ts/.tsx, excludes `*.test.ts` /
    // `*.int.test.ts`, and skips `__name__` directories — the last of which is
    // load-bearing here: image-internal-imports.test.ts plants a transient
    // fixture route under src/app/api mid-run, and racing its lifetime from a
    // parallel worker made this census flaky.
    for (const absolute of ROOTS.flatMap((root) => sourceFilesUnder(root))) {
      const file = repoRelative(absolute);
      for (const name of importedInternalNames(fs.readFileSync(absolute, "utf8"))) actual[name]?.push(file);
    }
    for (const files of Object.values(actual)) files.sort();

    expect(actual).toEqual(
      Object.fromEntries(Object.entries(APPROVED).map(([name, files]) => [name, [...files].sort()])),
    );
  });
});
