import { defineAttributeGroup } from "../../types";
import { MATERIAL_COLORS } from "../../shared-values";

/** Wings — visible fantasy morphology, gated by bodyFeatures group "wings". */
export const wingsGroup = defineAttributeGroup("wings", [
  {
    id: "wings.type",
    label: "Wing type",
    kind: "physical",
    category: "wings",
    valueType: "enum",
    description: "The structural style of the wings.",
    mutability: "inherent",
    allowedValues: ["membranous", "feathered", "insectoid", "gossamer", "draconic", "skeletal", "ethereal"],
    bodyLocationId: "wings",
    aliases: ["wing type", "bat wings", "feathered wings", "dragon wings"],
    promptHints: [
      "Visible fantasy morphology; describe as part of the always-visible appearance.",
      "membranous = bat-like (succubus/demon); feathered = avian/angelic; insectoid/gossamer = fae; draconic = scaled membrane; ethereal = wings of light or mist.",
    ],
  },
  {
    id: "wings.shape",
    label: "Wing shape",
    kind: "physical",
    category: "wings",
    valueType: "enum",
    description: "Finer visual form within the wing type — e.g. butterfly vs dragonfly for insectoid (fae) wings.",
    mutability: "inherent",
    allowedValues: ["butterfly", "dragonfly"],
    bodyLocationId: "wings",
    aliases: ["wing shape", "butterfly wings", "dragonfly wings"],
    promptHints: [
      "butterfly = broad, rounded, colorful scaled wings; dragonfly = long, narrow, iridescent twin pairs.",
    ],
  },
  {
    id: "wings.span",
    label: "Wing span",
    kind: "physical",
    category: "wings",
    valueType: "enum",
    description: "How large the wings read relative to the body.",
    mutability: "inherent",
    allowedValues: ["small", "medium", "large", "expansive"],
    bodyLocationId: "wings",
    aliases: ["wing span", "wing size"],
  },
  {
    id: "wings.color",
    label: "Wing color",
    kind: "physical",
    category: "wings",
    valueType: "enum_list",
    description: "Wing color, pattern, or surface material only — never size or shape. One or two from the material palette.",
    mutability: "inherent",
    allowedValues: [...MATERIAL_COLORS],
    bodyLocationId: "wings",
    aliases: ["wing color"],
    promptHints: ["e.g. crimson (leathery), jet_black, bone_white (feathers), iridescent (gossamer), smoke_grey."],
  },
  {
    id: "wings.carriage",
    label: "Wing carriage",
    kind: "presentation",
    category: "wings",
    valueType: "enum",
    description: "How the character usually holds their wings.",
    mutability: "mutable",
    allowedValues: ["folded", "half_spread", "spread", "relaxed"],
    bodyLocationId: "wings",
    aliases: ["wing posture", "wings folded"],
  },
]);
