import { defineAttributeGroup } from "../../types";

/**
 * Breasts — intimate region, gated by the body-config group "breasts" (distinct
 * from the always-present `chest` silhouette). Clinical values; prose promptHints.
 * Surfaces only as far as wardrobe exposure + the exposure mask allow.
 */
export const breastsGroup = defineAttributeGroup("breasts", [
  {
    id: "breasts.size",
    label: "Breast size",
    kind: "physical",
    category: "breasts",
    valueType: "enum",
    description: "Breast size as it reads unclothed.",
    mutability: "inherent",
    allowedValues: [
      "flat",
      "nearly_flat",
      "small",
      "modest",
      "average",
      "full",
      "large",
      "very_large",
      "heavy",
      "massive",
    ],
    bodyLocationId: "breasts",
    aliases: ["breast size", "cup size", "bust"],
    imageReveal: "shape",
    promptHints: [
      "Describe breasts only as far as wardrobe exposure and the exposure mask allow; one impression, not a checklist.",
    ],
  },
  {
    id: "breasts.shape",
    label: "Breast shape",
    kind: "physical",
    category: "breasts",
    valueType: "enum",
    description: "The overall shape the breasts present.",
    mutability: "inherent",
    allowedValues: [
      "round",
      "teardrop",
      "soft",
      "pert",
      "conical",
      "wide_set",
      "close_set",
      "pendulous",
      "saggy",
    ],
    bodyLocationId: "breasts",
    aliases: ["breast shape"],
    imageReveal: "shape",
  },
  {
    id: "breasts.augmentation",
    label: "Augmentation",
    kind: "physical",
    category: "breasts",
    valueType: "enum",
    description:
      "Whether the breasts are natural or surgically augmented, and how obviously it reads.",
    mutability: "mutable",
    allowedValues: ["natural", "subtly_augmented", "obviously_augmented"],
    bodyLocationId: "breasts",
    aliases: ["implants", "boob job", "fake breasts", "augmented"],
    imageReveal: "shape",
  },
  {
    id: "breasts.fullness",
    label: "Breast fullness",
    kind: "physical",
    category: "breasts",
    valueType: "enum",
    description:
      "How full and plump the breasts appear, especially from the side or when squeezed.",
    mutability: "mutable",
    allowedValues: [
      "deflated",
      "soft",
      "supple",
      "plump",
      "swollen",
      "overfull",
    ],
    bodyLocationId: "breasts",
    imageReveal: "shape",
  },
  {
    id: "breasts.nipples",
    label: "Nipples",
    kind: "physical",
    category: "breasts",
    valueType: "enum",
    description: "Nipple character and prominence when the chest is bare.",
    mutability: "inherent",
    allowedValues: [
      "small",
      "average",
      "large",
      "thick",
      "puffy",
      "inverted",
      "prominent",
      "long",
    ],
    bodyLocationId: "nipples",
    aliases: ["nipples"],
    imageReveal: "skin",
  },
  {
    id: "breasts.areola",
    label: "Areola",
    kind: "physical",
    category: "breasts",
    valueType: "enum",
    description: "Areola size and relief.",
    mutability: "inherent",
    allowedValues: [
      "small",
      "average",
      "large",
      "wide",
      "puffy",
      "prominent",
    ],
    bodyLocationId: "nipples",
    aliases: ["areola", "areolas"],
    imageReveal: "skin",
  },
  {
    id: "breasts.areola_color",
    label: "Areola color",
    kind: "physical",
    category: "breasts",
    valueType: "enum",
    description: "Natural pigmentation of the areolas and nipples.",
    mutability: "inherent",
    allowedValues: [
      "pale_pink",
      "soft_pink",
      "rose",
      "deep_pink",
      "tan",
      "brown",
      "dark_brown",
    ],
    bodyLocationId: "nipples",
    aliases: ["areola color", "nipple color"],
    imageReveal: "skin",
  },
]);
