import { defineAttributeGroup } from "../../types";
import {
  INTIMATE_SCENT_BASE,
  INTIMATE_SCENT_GUIDANCE,
  INTIMATE_TASTE_BASE,
  INTIMATE_TASTE_GUIDANCE,
} from "../../shared-values";

/**
 * Vulva — intimate region, gated by the body-config group "vulva" (which also
 * realizes the internal vagina + the labia/clitoris/vestibule sub-locations).
 * Clinical values; prose promptHints. Surfaces only at the intimate exposure tier.
 */
export const vulvaGroup = defineAttributeGroup("vulva", [
  // === Core Shape & Structure ===
  {
    id: "vulva.shape",
    label: "Vulva shape",
    kind: "physical",
    category: "vulva",
    valueType: "enum",
    description:
      "Overall silhouette and presentation of the vulva when legs are together or slightly parted.",
    mutability: "inherent",
    allowedValues: [
      "neat_slit",
      "innies",
      "puffy",
      "protruding",
      "plump_mound",
      "outies",
      "compact",
      "full",
      "high_set",
      "low_set",
      "pronounced",
    ],
    bodyLocationId: "vulva",
    aliases: ["vulva", "pussy", "mound"],
    promptHints: [
      "Used for clothed or partially clothed descriptions. Only describe visible contours.",
    ],
  },
  {
    id: "vulva.mons",
    label: "Mons pubis",
    kind: "physical",
    category: "vulva",
    valueType: "enum",
    description: "Fullness, roundness, and prominence of the pubic mound.",
    mutability: "inherent",
    allowedValues: [
      "flat",
      "soft",
      "plump",
      "prominent",
      "rounded",
      "high",
      "low",
      "padded",
      "firm",
      "fleshy",
    ],
    bodyLocationId: "mons",
  },

  // === Labia ===
  {
    id: "vulva.labia_majora",
    label: "Labia majora",
    kind: "physical",
    category: "vulva",
    valueType: "enum",
    description: "Fullness, separation, and tone of the outer lips.",
    mutability: "inherent",
    allowedValues: [
      "thin",
      "full",
      "puffy",
      "firm",
      "soft",
      "asymmetric",
      "sagging",
      "thick",
      "meaty",
      "smooth",
      "wrinkled",
    ],
    bodyLocationId: "labia_majora",
  },
  {
    id: "vulva.labia_minora",
    label: "Labia minora",
    kind: "physical",
    category: "vulva",
    valueType: "enum",
    description: "Visibility, size, and presentation of the inner lips.",
    mutability: "inherent",
    allowedValues: [
      "hidden",
      "tucked",
      "even",
      "protruding",
      "ruffled",
      "long",
      "asymmetric",
      "thick",
      "delicate",
      "frilled",
      "extended",
      "butterfly",
    ],
    bodyLocationId: "labia_minora",
    aliases: ["inner lips", "labia"],
    promptHints: [
      "Anatomical detail surfaces only at the intimate exposure tier.",
    ],
  },
  {
    id: "vulva.labia_color",
    label: "Labia color",
    kind: "physical",
    category: "vulva",
    valueType: "enum",
    description: "Natural pigmentation of the labia (both majora and minora).",
    mutability: "inherent",
    allowedValues: [
      "pale_pink",
      "soft_pink",
      "rose",
      "deep_pink",
      "mauve",
      "brown",
      "dark_brown",
      "purplish",
      "dusky",
      "reddish",
      "wine",
      "near_black",
    ],
    bodyLocationId: "vulva",
  },
  {
    id: "vulva.inner_color",
    label: "Inner color",
    kind: "physical",
    category: "vulva",
    valueType: "enum",
    description: "Pigmentation of the inner labia and vaginal entrance — deeper than the outer labia.",
    mutability: "inherent",
    allowedValues: ["pale_pink", "soft_pink", "rose", "deep_pink", "red", "dark_red", "mauve", "purplish"],
    bodyLocationId: "vestibule",
    promptHints: ["Surfaces only at the intimate exposure tier, when the inner vulva is visible."],
  },

  // === Clitoris ===
  {
    id: "vulva.clitoris",
    label: "Clitoris",
    kind: "physical",
    category: "vulva",
    valueType: "enum",
    description: "Prominence and size of the clitoris when not aroused.",
    mutability: "inherent",
    allowedValues: [
      "subtle",
      "small",
      "average",
      "prominent",
      "large",
      "hooded_only",
      "very_prominent",
      "pearl-like",
    ],
    bodyLocationId: "clitoris",
    aliases: ["clit"],
  },
  {
    id: "vulva.clitoral_hood",
    label: "Clitoral hood",
    kind: "physical",
    category: "vulva",
    valueType: "enum",
    description: "How the clitoral hood presents and its coverage.",
    mutability: "inherent",
    allowedValues: [
      "tight",
      "hooded",
      "retracted",
      "thick",
      "thin",
      "prominent",
      "loose",
      "covering",
      "partial",
    ],
    bodyLocationId: "clitoris",
  },

  // === Pubic Hair ===
  {
    id: "vulva.pubic_hair_density",
    label: "Pubic hair density",
    kind: "physical",
    category: "vulva",
    valueType: "enum",
    description: "Amount of pubic hair present.",
    mutability: "mutable",
    allowedValues: [
      "none",
      "sparse",
      "light",
      "moderate",
      "thick",
      "dense",
      "heavy",
      "wild",
    ],
    // "none" here IS the look (fully bare) — elided, the narrator/render is free
    // to imagine hair, so it survives the prompt-side "none" elision.
    renderNoneInPrompts: true,
    narratorGuidance: {
      none: "fully bare — no hair at all",
    },
    bodyLocationId: "mons",
  },
  {
    id: "vulva.pubic_hair_style",
    label: "Pubic hair style",
    kind: "physical",
    category: "vulva",
    valueType: "enum",
    description: "How the pubic hair is naturally grown or maintained.",
    mutability: "mutable",
    allowedValues: [
      "natural",
      "trimmed",
      "triangle",
      "landing_strip",
      "stubble",
      "smooth",
      "patchy",
      "heart",
      "brazilian",
      "full_bush",
      "shaved_clean",
      "sculpted",
    ],
    bodyLocationId: "mons",
  },

  // === Texture & Feel ===
  {
    id: "vulva.texture",
    label: "Vulva texture",
    kind: "physical",
    category: "vulva",
    valueType: "enum",
    description: "Surface feel of the vulva when touched.",
    mutability: "inherent",
    allowedValues: [
      "smooth",
      "soft",
      "velvety",
      "silky",
      "slightly_textured",
      "plump",
      "delicate",
      "meaty",
      "wrinkled",
      "ribbed",
    ],
    bodyLocationId: "vulva",
    promptHints: [
      "Primarily used during intimate physical contact descriptions.",
    ],
  },

  // === Mutable / Arousal States ===
  {
    id: "vulva.swelling",
    label: "Vulva swelling",
    kind: "physical",
    category: "vulva",
    valueType: "enum",
    description:
      "How much the vulva visibly swells and puffs when aroused — a response tendency, not live state (current arousal rides the arousal meter).",
    mutability: "mutable",
    allowedValues: ["none", "slight", "puffy", "moderate", "heavy", "engorged", "distended"],
    // A response tendency where the absence IS the information: "none" pins down
    // that she doesn't swell — elided, the narrator defaults to engorgement
    // writing at high arousal.
    renderNoneInPrompts: true,
    narratorGuidance: {
      none: "doesn't visibly swell or puff, even fully aroused",
    },
    bodyLocationId: "vulva",
    promptHints: [
      "Only surfaces when arousal is high or during close examination.",
    ],
  },
  {
    id: "vulva.wetness",
    label: "Natural wetness",
    kind: "physical",
    category: "vulva",
    valueType: "enum",
    description:
      "How wet she gets when aroused — the natural lubrication response, not live state (current arousal rides the arousal meter).",
    mutability: "mutable",
    allowedValues: [
      "dry",
      "dewy",
      "thin",
      "slick",
      "slippery",
      "glistening",
      "creamy",
      "viscous",
      "dripping",
      "soaking",
    ],
    bodyLocationId: "vulva",
    promptHints: ["Rendered only at intimate exposure or touch tier."],
  },
  {
    id: "vulva.tightness",
    label: "Baseline tightness",
    kind: "physical",
    category: "vulva",
    valueType: "enum",
    description:
      "Baseline vaginal tightness — a tendency that shifts with arousal and use, not live state (current arousal rides the arousal meter).",
    mutability: "mutable",
    allowedValues: ["loose", "relaxed", "average", "snug", "tight", "very_tight"],
    bodyLocationId: "vagina",
    promptHints: ["Only surfaces during intimate contact."],
  },

  // === Sensory ===
  {
    id: "vulva.scent",
    label: "Vulva scent",
    kind: "sensory",
    category: "vulva",
    valueType: "enum",
    description: "Intimate scent; shifts with hygiene, cycle, and arousal.",
    mutability: "mutable",
    allowedValues: [...INTIMATE_SCENT_BASE, "sweet", "salty", "fermented", "floral_musk"],
    bodyLocationId: "vulva",
    promptHints: [
      "Surfaces only at close/intimate range when scent is earned.",
    ],
    narratorGuidance: {
      ...INTIMATE_SCENT_GUIDANCE,
      sweet: "an unexpectedly sweet, honeyed note",
      salty: "clean sweat-salt over warm skin",
      fermented: "a tangy, sourdough ferment note",
      floral_musk: "musk with an incongruous floral sweetness laid over it",
    },
  },
  {
    id: "vulva.taste",
    label: "Vulva taste",
    kind: "sensory",
    category: "vulva",
    valueType: "enum",
    description: "Taste when orally stimulated.",
    mutability: "mutable",
    allowedValues: [...INTIMATE_TASTE_BASE, "sweet", "creamy"],
    bodyLocationId: "vulva",
    promptHints: ["Only surfaces at the intimate taste tier (oral contact)."],
    narratorGuidance: {
      ...INTIMATE_TASTE_GUIDANCE,
      sweet: "distinctly sweet — a honeyed taste",
      creamy: "a thick, rounded, dairy-soft note on the tongue",
    },
  },
]);
