import { defineAttributeGroup } from "../types";

// Narrator-gloss authoring batch — DRAFTS AWAITING
// OWNER REVIEW. Each gloss stays strictly in its own dimension per the orthogonality
// rule: frame speaks bone gauge (never height/weight), musculature speaks muscle only,
// weight speaks adiposity only. Sparse — self-evident members (average) stay bare.

export const buildGroup = defineAttributeGroup("build", [
  {
    id: "build.height",
    label: "Height",
    kind: "physical",
    category: "build",
    valueType: "enum",
    description: "Overall height as it visibly reads.",
    mutability: "inherent",
    allowedValues: [
      "very_short",
      "short",
      "below_average",
      "average",
      "above_average",
      "tall",
      "very_tall",
      "towering",
    ],
    aliases: ["height", "tall", "short", "petite"],
    imageAppearance: { class: "reinforcement", minimumFraming: "full_figure" },
    promptHints: [
      'Convey height through comparison and blocking ("she has to look up at him"), never as a number.',
    ],
    coreVisual: true,
    defaultValue: "average",
  },
  {
    id: "build.frame",
    label: "Frame",
    kind: "physical",
    category: "build",
    valueType: "enum",
    description:
      "Skeletal gauge — bone structure and joint heft, independent of height and weight.",
    mutability: "inherent",
    allowedValues: [
      "delicate",
      "slight",
      "average",
      "sturdy",
      "heavy_boned",
    ],
    aliases: ["frame", "build", "figure", "physique", "bone structure"],
    imageAppearance: { class: "core", referenceFreeRequired: true, minimumFraming: "portrait" },
    coreVisual: true,
    defaultValue: "slight",
    narratorGuidance: {
      delicate: "fine, bird-light bones — thin wrists and ankles",
      slight: "lightly built bone, a step up from delicate",
      sturdy: "dense, solid bone — thick at wrist and joint",
      heavy_boned: "big-jointed and thick-framed, heavy bone throughout",
    },
  },
  {
    id: "build.musculature",
    label: "Musculature",
    kind: "physical",
    category: "build",
    valueType: "enum",
    description: "Visible muscle development.",
    mutability: "mutable",
    renderVisual: true,
    allowedValues: [
      "untoned",
      "lightly_toned",
      "sinewy",
      "toned",
      "defined",
      "muscular",
      "powerfully_built",
    ],
    aliases: ["muscles", "muscle tone", "musculature"],
    imageAppearance: { class: "core", minimumFraming: "portrait" },
    narratorGuidance: {
      untoned: "no muscle definition — soft and unworked",
      lightly_toned: "the faintest firmness, barely worked",
      sinewy: "lean, wiry cord and tendon — no bulk",
      toned: "clearly fit and firm, definition without size",
      defined: "sharp, visible separation between muscles",
      muscular: "substantial, obvious muscle mass",
      powerfully_built: "heavy, powerful muscle — built for force",
    },
  },
  {
    id: "build.weight_presentation",
    label: "Weight presentation",
    kind: "physical",
    category: "build",
    valueType: "enum",
    description: "How body weight visibly presents.",
    mutability: "mutable",
    renderVisual: true,
    allowedValues: [
      "underweight",
      "slim",
      "average",
      "soft",
      "plump",
      "heavy",
      "very_heavy",
    ],
    aliases: ["weight", "body weight"],
    imageAppearance: { class: "core", referenceFreeRequired: true, minimumFraming: "portrait" },
    promptHints: [
      "Describe weight as silhouette and presence, never as a number or a judgement.",
    ],
    narratorGuidance: {
      underweight: "visibly thin — the edges of bone showing",
      slim: "lean and light, little softness carried",
      soft: "a gentle layer of softness over the body",
      plump: "rounded and full, softness carried everywhere",
      heavy: "carries real weight — full and substantial",
      very_heavy: "large-bodied; the weight is the first impression",
    },
  },
]);
