import { defineAttributeGroup } from "../types";

export const eyesGroup = defineAttributeGroup("eyes", [
  {
    id: "eyes.color",
    label: "Eye color",
    kind: "physical",
    category: "eyes",
    valueType: "enum",
    description: "Iris color.",
    mutability: "inherent",
    allowedValues: [
      "brown", "dark_brown", "hazel", "amber", "green", "emerald",
      "blue", "ice_blue", "gray", "gray_green", "violet", "heterochromatic",
      // Supernatural iris colors — selectable / forge-pickable, never auto-defaulted.
      "gold", "red", "crimson", "silver", "white", "solid_black",
    ],
    autoDefaultExcludes: ["gold", "red", "crimson", "silver", "white", "solid_black"],
    bodyLocationId: "eyes",
    aliases: ["eye color", "eye colour"],
    coreVisual: true,
    defaultValue: "brown",
  },
  {
    id: "eyes.pupil",
    label: "Pupil shape",
    kind: "physical",
    category: "eyes",
    valueType: "enum",
    description: "Pupil shape; anything but round reads as non-human.",
    mutability: "inherent",
    allowedValues: ["round", "vertical_slit", "horizontal_slit", "goat"],
    bodyLocationId: "eyes",
    aliases: ["pupils", "slit pupils"],
    promptHints: ["Vertical-slit pupils read demonic/feline, horizontal/goat bestial; round is the human default."],
  },
  {
    id: "eyes.luminosity",
    label: "Eye luminosity",
    kind: "physical",
    category: "eyes",
    valueType: "enum",
    description: "Whether the eyes give off their own light.",
    mutability: "inherent",
    allowedValues: ["none", "faint_glow", "glowing"],
    bodyLocationId: "eyes",
    aliases: ["glowing eyes"],
    promptHints: ["A supernatural cue; let it read strongest in low light."],
  },
  {
    id: "eyes.shape",
    label: "Eye shape",
    kind: "physical",
    category: "eyes",
    valueType: "enum",
    description: "Eye shape and set.",
    mutability: "inherent",
    renderVisual: true,
    allowedValues: [
      "almond", "round", "hooded", "monolid", "upturned",
      "downturned", "deep_set", "wide_set", "close_set", "narrow",
    ],
    bodyLocationId: "eyes",
    aliases: ["eye shape"],
  },
]);
